version: '3'

services:

  broker-service:
    build: 
      context: "./../broker-service"
      dockerfile: "./../broker-service/dockerfile"

    restart: always
    ports:
      - "3001:3001"

    deploy:
      mode: replicated
      replicas: 1

    extra_hosts:
    - "host.docker.internal:host-gateway"

  postgres:
    image: 'postgres:14.0'

    ports:
      - "5432:5432"

    restart: always

    deploy:
      mode: replicated
      replicas: 1

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users

    volumes:
      - "./data/postgres:/var/lib/postgresql/data/"

  authentication-service:
    build: 
      context: "./../authentication-service"
      dockerfile: "./../authentication-service/dockerfile"

    restart: always
    ports:
      - "3002:3001"

    deploy:
      mode: replicated
      replicas: 1

    extra_hosts:
    - "host.docker.internal:host-gateway"

    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"


