#  Base (heavier) image
FROM golang:1.18-alpine as base

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN go build -o authApp ./cmd/api

# Lighter image (contains just executable)

FROM alpine:latest

RUN mkdir /app

COPY --from=base /app/authApp /app

CMD ["/app/authApp"]